src/codegen.rs, src/eval.rs, src/ir.rs, src/main.rs, src/ty.rs
This moves the IR to MIR. It should have parity with the previous IR, which support functions, function calls, structs, and struct inits.
I've also gone ahead and adapted to using the Ty struct from the on-going type system work.
=> Moving IR to MIR

src/ide.rs, src/main.rs, src/tests.rs
Moved the big internaltest test to a separate file. Eventually, this may just become a series of unit tests. 
Moved the IDE support out of main into its own file.
=> Refactor main for cleanliness

src/parser/ast/debug.rs
This removes unneeded lifetime bounds on the recommendation of the recent Rust compiler update.
=> Fix build error with recent Rust nightly

lark/client/package-lock.json, lark/client/package.json, lark/package-lock.json, lark/package.json, src/ide.rs
Adds support for completions in the LSP implementation. The currently returns some example data.
Also fixes some leftover copy pasta in the package.json files.
=> Add support for completions. Clean up package.jsons

lark/.vscode/launch.json, src/ide.rs, src/main.rs, src/task_manager.rs
This PR adds a task manager to Lark. Currently, this is only used for LSP/IDE support.
The task manager will stand up other necessary subsystems to answer queries. Currently, this is the LSP server and a fake type checker.  It then establishes communication channels between itself and the subsystems.
Once live, requests come in via the LSP server. These requests are send to the task manager, which turns them into recipes to accomplish the task. These recipes the steps needed to be completed by the various subsystems to complete the tasks. The task manager will receive the answer to each step, and delegate out the previous answer to the next step in the recipe.
This allows the task manager to be the single point of coordination. This will allow for the future ability to prioritize steps …
=> Add task manager

Cargo.lock, Cargo.toml, components/codegen/Cargo.toml, components/codegen/src/lib.rs, components/eval/Cargo.toml, components/eval/src/lib.rs, components/ide/Cargo.toml, components/ide/src/lib.rs, components/ir/Cargo.toml, components/ir/src/lib.rs, components/task_manager/Cargo.toml, components/task_manager/src/lib.rs, src/hir.rs, src/hir/query_definitions.rs, src/main.rs, src/tests.rs, src/ty.rs, src/ty/map_family.rs, src/type_check.rs, src/type_check/base_only.rs, src/type_check/hir_typeck.rs, src/type_check/ops.rs, src/type_check/query_definitions.rs
This begins refactoring the project into separate crates in a workspace. Each of these subproject crates now lives in a "components" directory.
So far, the following crates have been moved:
* codegen
* eval
* ide
* ir
* task_manager
=> Begin workspace refactor

Cargo.lock, components/ast/Cargo.toml, components/ast/src/item_id.rs, components/ast/src/lib.rs, components/ast/src/parser_state.rs, components/ast/src/query_definitions.rs, components/ast/src/test.rs, components/indices/src/lib.rs, components/parser/Cargo.toml, components/parser/src/ast.rs, components/parser/src/ast/test_helpers.rs, components/parser/src/lib.rs, components/parser/src/program.rs, src/parser2/quicklex.rs, src/parser2/test_helpers.rs
Very simple implementations for the AST queries as well as some tests.
Also shows how `debug_with` should work, I think -- the idea is that you can do `foo.debug_with(db)` with anything and get a nice debug print-out, though in general we should implement `DebugWith` to rely on the `Has` traits for interners and things, so that you can do `foo.debug_with(bar)` for other things that are not the database. (In particular, I want to be able to do `ty.debug_with(unify)` to debug with the unifier.)
=> implement some of the AST queries

components/ide/src/lib.rs, components/task_manager/src/lib.rs
This adds a simple cancellation step to the task manager. Right now, it just removes the task. We can extend this to do more in the future.
=> Add cancellation action to task manager

Cargo.lock, Cargo.toml, components/ast/Cargo.toml, components/ast/src/item_id.rs, components/ast/src/lib.rs, components/debug/src/lib.rs, components/intern/Cargo.toml, components/intern/src/lib.rs, components/lark-debug-derive/Cargo.toml, components/lark-debug-derive/src/lib.rs, components/lark-string/Cargo.toml, components/lark-string/src/lib.rs, components/lark-string/src/main.rs, components/map/src/lib.rs, components/parser/src/lib.rs, components/parser/src/parser/program.rs
I was working towards moving everything onto one intern + debug infrastructure. Didn't quite get there, but here is how far I got.
Most notable thing:
You can now do `#[derive(Debug, DebugWith)]` to get the `debug_with` helpers. This relies on specialization so you need to add that feature. Note that all types must implement `DebugWith` for **any** context. This means that if you want to have a specialized `DebugWith` impl, you also need a fallback -- the macro `debug::debug_fallback_impl` helpfully provides such a fallback for you, using `std::fmt::Debug`.
=> refactorings towards merging parser etc

Cargo.lock, Cargo.toml, components/ast/src/lib.rs, components/ast/src/parser_state.rs, components/ide/src/lib.rs, components/query/Cargo.toml, components/query/src/lib.rs, components/task_manager/Cargo.toml, components/task_manager/src/lib.rs, src/main.rs
This PR adds a query system, based on the existing salsa support, that can handle queries from the LSP side. Currently, the only thing it can do is open a file with known contents, and to return these on a hover request.
=> Add in query system with salsa support

lark/client/package.json, lark/package.json
Bump the required VSCode version to prevent errors in dependent .d.ts files.
=> Bump the required VSCode version

.travis.yml, components/lark-codegen/src/build.rs, components/lark-codegen/src/codegen_c.rs, components/lark-codegen/src/codegen_rust.rs, components/lark-codegen/src/lib.rs, components/lark-eval/src/lib.rs, components/lark-mir/src/lib.rs, tests/common/mod.rs, tests/compile.rs
This PR adds C codegen support to Unix and Windows. The support is still very basic and currently only supports basic types and structs.
This PR also removes string interpolation from the MIR, as it was decided this was not the best place for it. The intent will be to add it back at a later time as systems mature.
=> Add C codegen support

components/lark-eval/src/lib.rs, tests/eval.rs
This adds a simple IO redirection for eval, so that we can test the output. Along with that, this adds the same tests codegen is using, bringing it up to parity.
=> Add testing support to eval

components/lark-language-server/src/lib.rs, components/lark-task-manager/src/lib.rs
This starts laying in some of the basics for reporting errors back to the IDE. So far, this is just the LSP piece, and a way to communicate through the LSP support. It does this by introducing a new Diagnostics member to LSPResponse. It should, in theory, be safe to send these whenever we encounter an error.
=> Add support for error reporting to lsp

.vscode/settings.json
I've had issues with RLS auto-updating the tools. Removing for now to help prevent broken rustup states.
=> Remove potentially dangerous vscode setting

Cargo.lock, components/lark-language-server/src/lib.rs, components/lark-query-system/Cargo.toml, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs, components/lark-task-manager/src/lib.rs, samples/challenge1.lark
This plumbs the error reporting from open/edit events back through to the IDE, so we can display when an error occurs. Currently, we don't display any text for the error message and instead use a generic "Error" message.
This PR also adds support for file editing events, and tracks those changes by applying the edits against the existing contents in the filemap.
=> Add error reporting to IDE. Also add file edits

components/lark-query-system/src/ls_ops.rs, samples/challenge1.lark
This adds a check for the types of entities and subentities, as well as signatures of files.
=> Add some type checking to error reporting

components/lark-query-system/src/ls_ops.rs, lark/build.bat, lark/build.sh, lark/package.json, src/main.rs
This PR adds a simpler way of building the vscode support. It also comments out the previous body typechecking, and minimizes logging to only error to prevent large files from overloading vscode.
=> Add helper functions to build vscode support. Minimize logging

components/lark-query-system/src/lib.rs
I plan to improve salsa API but this (might?) prevent deadlocks in the meantime
=> try to workaround non-reentrant read locks

Cargo.lock, Cargo.toml, components/ast/Cargo.toml, components/ast/src/test.rs, components/hir/Cargo.toml, components/lark-language-server/src/lib.rs, components/lark-query-system/Cargo.toml, components/lark-query-system/src/lib.rs, components/lark-task-manager/Cargo.toml, components/lark-task-manager/src/lib.rs, components/lark-type-check/Cargo.toml, src/main.rs
This helps us to always respond promptly.
Also, upgrade to Salsa 0.8.0, which has a cleaned up API that features fewer footguns. =)
=> discard messages if there are pending mutations

.travis.yml, Cargo.lock, Cargo.toml, components/hir/src/fn_body.rs, components/hir/src/lib.rs, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs, components/lark-type-check/src/hir_typeck.rs, components/lark-type-check/src/query_definitions.rs, src/build.rs, src/main.rs
Anecdotally, seems to work as I edit things -- of course the only stuff that HIR lowering supports is basically variable names.
I added `build foo` as a way to debug problems outside of the LS:
```bash
> cargo run -- build samples/challenge1.lark
Finished dev [optimized + debuginfo] target(s) in 0.16s
Running `target/debug/lark build samples/challenge1.lark`
Lark: executing
error: something is wrong here =)
- <samples/challenge1.lark>:6:18
6 | def new(msg: own String, level: String) -> Diagnostic {
|                  ^^^^^^
error: something is wrong here =)
- <samples/challenge1.lark>:6:33
6 | def new(msg: own String, level: String) -> Diagnostic {
|                                 ^^^^^^
```
=> patch up holes in type-check, add a way to run w/o the LS

tests/language_server.rs
Use drop on our session, so we can close the child process whenever we finish or an assertion is thrown. This helps simplify the unit tests down to a more reasonable amount of code.
=> Clean up LSP test code to use drop

Cargo.lock, Cargo.toml, components/ast/Cargo.toml, components/ast/src/lib.rs, components/ast/src/query_definitions.rs, components/lark-error/Cargo.toml, components/lark-error/src/lib.rs, components/lark-hir/Cargo.toml, components/lark-hir/src/lib.rs, components/lark-hir/src/query_definitions.rs, components/lark-hir/src/type_conversion.rs, components/lark-parser/Cargo.toml, components/lark-parser/src/lib.rs, components/lark-parser/src/macros/struct_declaration.rs, components/lark-parser/src/parser.rs, components/lark-parser/src/query_definitions.rs, components/lark-parser/src/syntax/list.rs, components/lark-seq/Cargo.toml, components/lark-seq/src/lib.rs, components/lark-seq/src/test.rs, components/lark-string/src/text.rs, components/lark-test/Cargo.toml, components/lark-test/src/lib.rs, components/lark-ty/Cargo.toml, components/lark-ty/src/lib.rs, components/lark-ty/src/map_family.rs
`Arc<Vec<T>>` is annoying.
`Seq<T>` is more convenient and nice.
We could move to a full blown persistent collection at some point but I suspect we won't need it really -- mostly we have vectors that we build up in some way and then clone a lot. 
This type supports also extracting subviews in case we ever want that (they share the same backing storage for now).
=> introduce a `Seq` type

components/intern/src/lib.rs, components/lark-entity/src/lib.rs, components/lark-parser/src/lib.rs, components/lark-parser/src/macros/function_declaration.rs, components/lark-parser/src/macros/struct_declaration.rs, components/lark-parser/src/syntax/fn_body.rs, components/lark-parser/src/syntax/type_reference.rs, components/lark-string/src/global.rs
I added that because `&impl AsRef<X>` didn't match `&dyn AsRef<X>`, but I realize now it *does* match `&&dyn AsRef<X>`.
=> replace `&(impl AsRef<X> + ?Sized)` with `&dyn AsRef<X>`

components/lark-query-system/src/ls_ops.rs, components/lark-type-check/src/hir_typeck.rs
This adds the missing support for struct init fields to find-all-references and goto-definition. This fixes https://github.com/lark-exploration/lark/issues/153 as well by fixing hovers for struct init fields.
=> Struct init field hover, goto-def, and find-all-refs

components/lark-parser/src/ir.rs, components/lark-parser/src/macros/function_declaration.rs, components/lark-parser/src/macros/struct_declaration.rs, components/lark-parser/src/syntax/entity.rs, components/lark-parser/src/syntax/expression/scope.rs, components/lark-parser/src/syntax/fn_body.rs, components/lark-parser/src/syntax/fn_signature.rs, components/lark-parser/src/syntax/member.rs, components/lark-parser/src/syntax/type_reference.rs, components/lark-parser/src/type_conversion.rs
Now that `ParserDatabase` is dyn-capable, we don't need it, we can just `ParserDatabase` directly.
=> remove `LazyParsedEntityDatabase` trait
