notes/type_system.md
Write out my thoughts on Lark type system thus far.
=> type system thoughts

src/arena.rs, src/indices.rs, src/main.rs, src/ty.rs, src/ty/context.rs, src/ty/intern.rs, src/ty/mode.rs, src/ty/query.rs
=> exploring mode composition and tweaking type system impl

Cargo.lock, Cargo.toml, src/ty.rs, src/ty/debug.rs, src/ty/unify/relate.rs, src/ty/unify/relate/perms.rs, src/ty/unify/relate/repr_eq.rs, src/ty/unify/relate/test.rs
Probably got some bugs, bug...
=> first shot at subtyping code

src/ide.rs
Added a simple hover example to show how to respond to a hover request.
=> A simple hover example

src/hir.rs, src/hir/query_definitions.rs, src/indices.rs, src/ty.rs, src/ty/base_inferred.rs, src/ty/base_only.rs, src/ty/declaration.rs, src/ty/identity.rs, src/ty/interners.rs, src/ty/map_family.rs, src/ty/substitute.rs, src/type_check.rs, src/type_check/base_only.rs, src/type_check/hir_typeck.rs, src/type_check/ops.rs, src/type_check/query_definitions.rs
This PR pushes more on the type-checker. It introduces placeholders to handle generics and basically "connects the dots" so that we are just ready to really *try it* on some inputs.
=> type-checker work

Cargo.lock, components/parser/Cargo.toml, components/parser/src/parser2/lite_parse.rs, components/parser/src/parser2/macros.rs
Arc seems like the easiest choice.
=> convert macro table to use trait objects

tests/compile.rs
Fix the windows test for codegen
=> Fix Windows test

components/hir/src/error.rs, components/hir/src/lib.rs, components/hir/src/query_definitions.rs, components/hir/src/scope.rs, components/hir/src/type_conversion.rs, components/lark-entity/src/lib.rs, components/parser/src/parser/lexer_helpers.rs, components/type-check/src/hir_typeck.rs
Trying to stand up some kind of RLS integration — a bit annoying since all this code will go away when @wycats finishes up.
=> push HIR resolution a bit further along

Cargo.lock, Cargo.toml, components/ast/Cargo.toml, components/ast/src/query_definitions.rs, components/hir/Cargo.toml, components/hir/src/error.rs, components/hir/src/fn_body.rs, components/hir/src/lib.rs, components/hir/src/query_definitions.rs, components/hir/src/scope.rs, components/hir/src/type_conversion.rs, components/lark-entity/src/lib.rs, components/lark-query-system/Cargo.toml, components/lark-query-system/src/lib.rs, components/ty/src/lib.rs, components/type-check/Cargo.toml, components/type-check/src/base_only.rs, components/type-check/src/hir_typeck.rs, components/type-check/src/lib.rs, components/type-check/src/ops.rs
We're now getting close to something that could end-to-end function in Language Server.
=> implement more HIR query handling

Cargo.lock, components/ast/Cargo.toml, components/ast/src/lib.rs, components/ast/src/parser_state.rs, components/ast/src/query_definitions.rs, components/ast/src/test.rs, components/lark-query-system/Cargo.toml, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs, components/parser/src/parser/pos.rs
The codemap integration will burn your eyes out. Don't look! Turn away!  I figure we're going to want to revisit this at some point anyhow when integrating @wycats's work.
Anyway, almost works. =)
=> almost get a working end-to-end query showing entity ids at position

.vscode/settings.json, components/parser/src/lib.rs, components/parser/src/parser.rs, components/parser/src/parser/test_helpers.rs, components/parser/src/parser2.rs, components/parser/src/parser2/builtins.rs, components/parser/src/parser2/builtins/def_def.rs, components/parser/src/parser2/builtins/expr_def.rs, components/parser/src/parser2/builtins/paired.rs, components/parser/src/parser2/builtins/struct_def.rs, components/parser/src/parser2/entity_tree.rs, components/parser/src/parser2/lite_parse.rs, components/parser/src/parser2/macros.rs, components/parser/src/parser2/quicklex.rs, components/parser/src/parser2/reader.rs, components/parser/src/parser2/test_helpers.rs, components/parser/src/parser2/token.rs, components/parser/src/parser2/token_macro.rs, components/parser/src/parser2/token_tree.rs, components/parser/src/prelude.rs
This PR adds support for extent tracking of structs and defs
=> Reader First Draft

.gitignore, Cargo.lock, Cargo.toml, components/ast/Cargo.toml, components/ast/src/lib.rs, components/ast/src/query_definitions.rs, components/ast/src/test.rs, components/hir/Cargo.toml, components/hir/src/lib.rs, components/hir/src/query_definitions.rs, components/lark-error/src/lib.rs, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs, components/parser/src/parser/ast/test_helpers.rs, components/parser/src/parser/grammar.lalrpop, components/parser/src/parser/grammar.rs, components/parser/src/parser/lexer_helpers.rs, components/parser/src/parser/pos.rs, components/parser/src/parser2/test_helpers.rs, samples/minimal.lark, src/main.rs
=> get nested entities query working

Cargo.lock, components/debug/src/lib.rs, components/lark-debug-derive/src/lib.rs, components/lark-entity/src/lib.rs, components/lark-query-system/Cargo.toml, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs, components/lark-string/src/lib.rs, components/parser/src/parser/program.rs, components/ty/Cargo.toml, components/ty/src/base_inferred.rs, components/ty/src/base_only.rs, components/ty/src/declaration.rs, components/ty/src/lib.rs, components/unify/Cargo.toml, components/unify/src/lib.rs, samples/minimal.lark
Though the formatting leaves..um..something to be desired. =) But good enough.
=> change hover text to show types

Cargo.lock, components/lark-codegen/Cargo.toml, components/lark-codegen/src/build.rs
This adds some logic to autodetect where cl.exe is, so that we can run it.
=> Auto-detect msvc location

components/parser/src/lib.rs, components/parser/src/parser2/builtins/def_def.rs, components/parser/src/parser2/builtins/struct_def.rs, components/parser/src/parser2/entity_tree.rs, components/parser/src/parser2/lite_parse.rs, components/parser/src/parser2/macros.rs, components/parser/src/parser2/reader.rs, components/parser/src/reporting.rs
=> Reader cleanup

Cargo.lock, components/ast/src/query_definitions.rs, components/hir/src/fn_body.rs, components/hir/src/scope.rs, components/hir/src/type_conversion.rs, components/lark-entity/src/lib.rs, components/lark-error/src/lib.rs, components/lark-query-system/Cargo.toml, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs, components/lark-ty/src/lib.rs, components/lark-type-check/src/base_only.rs, components/lark-type-check/src/hir_typeck.rs, components/lark-type-check/src/lib.rs, components/lark-type-check/src/ops.rs, components/lark-type-check/src/query_definitions.rs, src/build.rs
This adds a label to go along with error spans, so that we can show a message with the error.
=> Added labels to error spans

components/hir/src/fn_body.rs, components/hir/src/lib.rs, components/hir/src/scope.rs, components/hir/src/type_conversion.rs, components/lark-entity/src/lib.rs, components/lark-type-check/src/base_only.rs, components/lark-type-check/src/hir_typeck.rs, components/lark-type-check/src/lib.rs, components/lark-type-check/src/ops.rs
This adds support for string constants in the lowering to HIR.
=> Lower string constants in HIR

components/debug/src/lib.rs, components/lark-error/src/lib.rs, components/lark-hir/src/fn_body.rs, components/lark-hir/src/lib.rs, components/lark-parser/src/lexer/definition.rs, components/lark-parser/src/lexer/test.rs, components/lark-parser/src/lexer/token.rs, components/lark-parser/src/parser.rs, components/lark-parser/src/syntax/fn_body.rs, components/lark-parser/src/syntax/matched.rs, components/lark-type-check/src/hir_typeck.rs, tests/parser/main.rs
Various bug fixes and tweaks to the expression parser. Implement `DebugWith` for HIR. etc.
=> further improve the expression parser

tests/language_server.rs, tests/test_files/struct.lark
Change hover test to be more interesting rather than looking for ""
=> Add more interesting hover test

Cargo.lock, components/lark-build/Cargo.toml, components/lark-build/src/codegen_rust.rs, components/lark-eval/Cargo.toml, components/lark-eval/src/lib.rs, components/lark-mir/src/fn_bytecode.rs, components/lark-mir/src/lib.rs, tests/backend.rs, tests/test_files/struct_init.lark
This adds aggregate to MIR as well as supporting aggregates and field access in compile and eval.
=> Add struct support to eval and compile

components/lark-hir/src/lib.rs, components/lark-parser/src/syntax/fn_body.rs
This is the first step into moving spans into their own table
=> Span refactor

components/lark-cli/src/repl.rs
This pretty prints an error when it occurs in the repl
=> Give better repl error

components/lark-eval/src/lib.rs
This finishes adding 'if' support into the new eval code
=> Add 'if' support to eval

components/lark-cli/src/lib.rs, components/lark-language-server/src/lib.rs, components/lark-parser/src/lib.rs, components/lark-parser/src/query_definitions.rs, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs, components/lark-task-manager/src/lib.rs, components/lark-type-check/src/lib.rs
This adds support for find all refs. It currently works for Field, Variable, and Entity places.
=> Add find all references

Cargo.lock, components/lark-actor/src/lib.rs, components/lark-language-server/Cargo.toml, components/lark-language-server/src/lib.rs, components/lark-query-system/src/lib.rs, components/lark-query-system/src/ls_ops.rs
Adds rename to the supported LSP comands.
=> Add rename to LSP support

components/lark-build/src/codegen_rust.rs, components/lark-debug-with/src/lib.rs, components/lark-entity/src/lib.rs, components/lark-error/src/lib.rs, components/lark-eval/src/lib.rs, components/lark-hir/src/lib.rs, components/lark-parser/src/syntax/fn_body.rs, components/lark-query-system/src/ls_ops.rs, components/lark-test/src/harness/test/hir_test.rs, components/lark-type-check/src/base_inference.rs, components/lark-type-check/src/full_inference/analysis.rs, components/lark-type-check/src/full_inference/analysis/builder.rs, components/lark-type-check/src/full_inference/analysis/dump.rs, components/lark-type-check/src/full_inference/analysis/initialization.rs, components/lark-type-check/src/full_inference/analysis/kind_inference.rs, components/lark-type-check/src/full_inference/query_definition.rs, components/lark-type-check/src/full_inference/type_checker.rs, components/lark-type-check/src/hir_typeck.rs, components/lark-type-check/src/lib.rs, components/lark-type-check/src/results.rs, tests/test_files/assign_variable.lark, tests/test_files/binary_expressions_precedence.hir, tests/test_files/initialization_inference/move_part.stderr, tests/test_files/initialization_inference/move_part_use_whole.lark, tests/test_files/initialization_inference/move_part_use_whole.stderr, tests/test_files/initialization_inference/move_twice.lark, tests/test_files/initialization_inference/move_twice.stderr, tests/test_files/initialization_inference/move_whole_use_part.lark, tests/test_files/initialization_inference/move_whole_use_part.stderr
we check for use of moved results
=> implement initialization check, fix some bugs

components/lark-type-check/src/full_inference/analysis/initialization.rs, tests/test_files/initialization_inference/move_other_field.lark
=> tweaks to the initialization analysis

Cargo.lock, components/lark-cli/Cargo.toml, components/lark-cli/src/build.rs, components/lark-language-server/Cargo.toml, components/lark-language-server/src/lib.rs, tests/test_files/assign_variable.lark
This removes some unused dependencies. Looks like it helps with build times a little on my box.
=> Remove unused dependencies

Cargo.lock, components/lark-cli/Cargo.toml, components/lark-cli/src/lib.rs, components/lark-cli/src/repl.rs, components/lark-entity/src/lib.rs, components/lark-hir/Cargo.toml, components/lark-hir/src/lib.rs, components/lark-parser/Cargo.toml, components/lark-parser/src/lib.rs, components/lark-query-system/Cargo.toml, components/lark-string/src/lib.rs, components/lark-test/Cargo.toml, components/lark-test/src/lib.rs, components/lark-ty/src/lib.rs, components/lark-type-check/Cargo.toml, components/lark-type-check/src/lib.rs, components/lark-unify/src/lib.rs
=> Update deps. Cleanup old flags

Cargo.lock, Cargo.toml, components/lark-actor/Cargo.toml, components/lark-build/Cargo.toml, components/lark-build/src/build.rs, components/lark-cli/Cargo.toml, components/lark-language-server/Cargo.toml, components/lark-parser/Cargo.toml, components/lark-query-system/Cargo.toml, components/lark-span/Cargo.toml, components/lark-test/Cargo.toml
This bumps our outdated deps. We should be up-to-date after this for the time being.
=> Update outdated deps

Cargo.lock, components/lark-cli/Cargo.toml, components/lark-hir/Cargo.toml, components/lark-parser/Cargo.toml, components/lark-parser/src/lib.rs, components/lark-query-system/Cargo.toml, components/lark-test/Cargo.toml, components/lark-type-check/Cargo.toml, components/lark-type-check/src/lib.rs
=> Bump salsa
